// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjoqzkfvcrctfvaanaqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqb3F6a2Z2Y3JjdGZ2YWFuYXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMjM5OTEsImV4cCI6MjA4Njc5OTk5MX0.hTyCCyt200e7JypDmbDgyTsh9Vu8Q_Mt53L5ZnC2HWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});